<?php

/**
 * @copyright Copyright (c) 2011 - 2013 Aleksandr Torosh (http://wezoom.com.ua)
 * @author Aleksandr Torosh <webtorua@gmail.com>
 */

$title = 'Редактирование виджета';
$this->tag->prependTitle($title);
?>

<p>
    <a href="/widget/admin/index" class="ui button">
        <i class="icon left"></i> Назад
    </a>
    <?php if (isset($widget)): ?>
        <a href="/widget/admin/delete/<?php echo $widget->getId() ?>" class="ui button red">
            <i class="icon trash"></i> Удалить
        </a>
    <?php endif; ?>
</p>

<form method="post" action="" class="ui form segment">
    <?php if (isset($widget)): ?>
        <p>ID = <b><?php echo $widget->getId() ?></b></p>
    <?php else: ?>
        <?php echo $form->renderDecorated('id'); ?>
    <?php endif; ?>
    <?php echo $form->renderDecorated('title'); ?>
    <?php echo $form->renderDecorated('html'); ?>
    <div class="ui positive submit button">
        <i class="save icon"></i> Сохранить
    </div>
</form>

<script>
    $('.ui.form').form({});
</script>

<link rel="stylesheet" href="/vendor/codemirror-4.2/lib/codemirror.css">
<link rel="stylesheet" href="/vendor/codemirror-4.2/theme/eclipse.css">

<script src="/vendor/codemirror-4.2/lib/codemirror.js"></script>
<script src="/vendor/codemirror-4.2/mode/htmlmixed/htmlmixed.js"></script>
<script src="/vendor/codemirror-4.2/mode/javascript/javascript.js"></script>
<script src="/vendor/codemirror-4.2/mode/css/css.js"></script>

<script>
    var myCodeMirror = CodeMirror.fromTextArea(document.getElementById('html'), {
        lineNumbers: true,               // показывать номера строк
        matchBrackets: true,             // подсвечивать парные скобки
        mode: 'html', // стиль подсветки
        indentUnit: 4,                    // размер табуляции
        theme: 'eclipse'
    });
</script>