<?php

/**
 * @copyright Copyright (c) 2011 - 2012 Aleksandr Torosh (http://wezoom.com.ua)
 * @author Aleksandr Torosh <webtorua@gmail.com>
 */

?>

<p>
    <a href="/widget/admin/add" class="ui positive button"><i class="add icon"></i> Добавить</a>
</p>

<table class="ui table segment">
    <thead>
        <tr>
            <th style="width:25%">ID</th>
            <th>Название</th>
        </tr>
    </thead>
    <tbody>
        <?php if (!empty($entries)): ?>
            <?php foreach ($entries as $el): ?>
                <?php $link = '/widget/admin/edit/' . $el->getId(); ?>
                <tr>
                    <td><a href="<?php echo $link; ?>"><?php echo $el->getId(); ?></a></td>
                    <td><a href="<?php echo $link; ?>"><?php echo $el->getTitle(); ?></a></td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </tbody>
</table>